### ISSUE TITLE
Unable to sell any equipment

### ISSUE THREAD

**Issue by dgteqp** [dgteqp/DEIMOBILE#1]
We are unable to "SELL" an equipment from any of our modules (Cranes / Rigs / Excavators / Dumpers / Generators ). 
As soon as we click submit after filling the equipment details , its showing "Unfortunately, DEI has stopped".

**Comment by degeqp** [comment]
We are now able to supply equipments for Sale.

**Comment by krayaprolu** [comment]
[Kesav Sept 17th, 2017] Fixed please re-test

**Comment by dgteqp** [comment]
We can neither Supply nor sell any equipment

**Comment by krayaprolu** [comment]
[Kesav Oct 11, 2017] This is fixed in the latest apk
