### ISSUE TITLE
My Account features are not working

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEIMOBILE#10]
We only have access to My Account to edit/update our personal info, but not for  :
My orders
My products
My jobs
Applied jobs
Change password

Please check out the following screenshot for a better understanding :
![screenshot_20170818-175538](https://user-images.githubusercontent.com/30520066/29459050-a9614bf2-843f-11e7-9aa1-9739f0befbb8.png)

**Comment by krayaprolu** [comment]
Currently only My Account has been implemented, rest of the features are not implemented, that is the reason for them being Greyed out, when implemented, they will be enabled.
