### ISSUE TITLE
App crashes at Ad-Payment Options

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEIMOBILE#15]
When we select the payment option/choice (after uploading the images), the App crashes.

**Comment by degeqp** [comment]
APP crashes when we hit "SUBMIT" button right after selecting the payment package.
By the way, please add "Promotional offer" 
Payment Options are not visible after adding images.

Check out the following screenshots before and after adding images:
![screenshot-kesav1](https://user-images.githubusercontent.com/30520066/30107560-c51a5820-931c-11e7-841d-3c5ace7d4dfb.png)
![screenshot-kesav2](https://user-images.githubusercontent.com/30520066/30107561-c51b9aa0-931c-11e7-9e75-2eeb4c017ba0.png)

AD Section is taking 10sec to show up 1st AD in Home Page
check out the following screenshot:
![screenshot-kesav3](https://user-images.githubusercontent.com/30520066/30107719-319f721e-931d-11e7-93c2-16ff4b92d556.png)

**Comment by krayaprolu** [comment]
[Kesav Sept 17th, 2017] Fixed, please re-test.
