### ISSUE TITLE
CHANGE ALL REFERENCES FROM "DEI" TO "BEI"

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEIMOBILE#22]
1.Change all references from DEI to BEI in UI and CODE
2.Change all originating e-mails from "info@bei" to "info@dei"

Note: info@bigequipmentsindia.com is functional and has the same password as indo@dei

**Comment by krayaprolu** [comment]
[Kesav Oct 2, 2017] This is fixed in the latest apk

**Comment by krayaprolu** [comment]
[Kesav Oct 11, 2017] This is fixed in the latest apk
