### ISSUE TITLE
Replace DEI Logo with BEI Logo in HOME PAGE

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEIMOBILE#30]
Replace DEI Logo with BEI Logo in "Home Page Header".

We are sending a screenshot for a better understanding:
![whatsapp image 2017-10-03 at 10 54 34 am](https://user-images.githubusercontent.com/30520066/31111187-e117946c-a829-11e7-9d9e-61df292089f8.jpeg)

**Comment by krayaprolu** [comment]
[Kesav Oct 11, 2017] This is fixed in the latest apk
