### ISSUE TITLE
URGENT : Images are not displayed after the Equipment is uploaded

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEIMOBILE#32]
When an equipment is uploaded, it is successfully uploaded but the images are not displaying in browse due to which the equipment is not showing up in the LIVE WEBSITE.

Jani sir said, even though the url of the image is listed in the image table, the actual image is not uploading to "uploads/2017/******/folder" .

**Comment by krayaprolu** [comment]
[Kesav Oct 11, 2017] This is fixed in the latest apk
