### ISSUE TITLE
Unable to supply any equipment

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEIMOBILE#4]
We are unable to "SUPPLY" equipments from any of our modules (Cranes /Rigs /Excavators /Dumpers / Generators).
As soon as we click submit after filling the equipment details , its showing "Unfortunately, DEI has stopped"

**Comment by degeqp** [comment]
At this time, we can only supply Cranes. But the App is not working for other equipment types

**Comment by degeqp** [comment]
At this time, we are unable to supply any of the equipments .
The APP is crashing after clicking the "SUBMIT" button .

**Comment by degeqp** [comment]
This issue is not fixed in the latest APK file provided.

**Comment by krayaprolu** [comment]
[Kesav Sept 17th, 2017] Fixed please re-test

**Comment by degeqp** [comment]
Unable to SUPPLY any EQUIPMENT in the LATEST APK File provided.

**Comment by krayaprolu** [comment]
[Kesav Oct 11, 2017] This is fixed in the latest apk
