### ISSUE TITLE
Hiring process is not generating E-mails

### ISSUE THREAD

**Issue by degeqp** [dgteqp/DEIMOBILE#7]
The user who hires an equipment is not receiving mails after successful check-availability request, but receiving an on screen message as shown in the below image :
![screenshot_20170818-144916](https://user-images.githubusercontent.com/30520066/29457638-d99368d4-8438-11e7-96d5-5d5d47f3dc7f.png)

**Comment by krayaprolu** [comment]
[Kesav Sept 17th, 2017] Fixed please re-test
